### ISSUE TITLE
regarding squid server terminating connection with https_proxy

### ISSUE THREAD

**Issue by ping2balaji** [aaronhackney/terraform_letsencrypt#1]
Hi Aaron,
Sorry to reach out to you this way as i could not find your contact email anywhere.
I would like to know if you have found a fix/solution to the following issue you have reported:
https://github.com/psf/requests/issues/5384#issuecomment-608948354

"After the 3-way handshake, request sends a push, squid responds with an ack, and then requests sends the connect message but the message is not encrypted in the TLS tunnel. After which, squid acknowledges receipt of the CONNECT and immediately follows with a TCP RESET.
The squid logs show this: NONE/000 0 NONE error:transaction-end-before-headers - HIER_NONE/- -"

Im facing same issue and would be helpful if you can provide some direction to overcome this. You help much appreciated.
I will promptly close/delete this bug from this repo.
Thanks
Balaji

**Comment by aaronhackney** [comment]
Hi sorry I never found an answer and moved on to other things.

**Comment by ping2balaji** [comment]
hi Aaron, thanks for the info. appreciate it.
